export default {
  splashLogo : require('./splashLogo.png'),
  splashLogo2 : require('./splashLogo2.png'),
  Arrowleft : require('./Arrowleft.png'),
  placeIndicate : require('./placeIndicate.png'),
  locationYellowMarker : require('./locationYellowMarker.png'),
  locationGreenMarker : require('./locationGreenMarker.png'),
  Car : require('./Car.png'),
  Bike : require('./Bike.png'),
  Cycle : require('./Cycle.png'),
  Taxi : require('./Taxi.png'),
  Fual : require('./Fual.png'),
  mph : require('./mph.png'),
  Speed : require('./Speed.png'),
  RightTick : require('./rightTick.png'),
  creditcard : require('./creditcard.png'),
  Airplane:require('./Airplane.png'),
  CityIcon:require('./CityIcon.png'),
  CarRental:require('./CarRental.png'),
  Motorcycle:require('./Motorcycle.png'),
  Call:require('./Call.png'),
  Message:require('./Message.png'),
  Navigation:require('./Navigator.png'),
  Plus:require('./Plus.png'),
  Mute:require('./Mute.png'),
  Unmute:require('./Unmute.png'),
  Video:require('./Video.png'),
  More:require('./Option.png'),
  Camera:require('./Camera.png'),
  FileUpload:require('./File.png'),
  CloseIcon:require('./Cancel.png'),
  LocationTarget:require('./LocationTarget.png'),
  navigation :require('./navigation.png'),
  sendMessage :require('./sendMessage.png'),
  Expand :require('./expand.png'),
};
